cart/urls.py
# from django.urls import path
# from cart import views
#
# app_name = 'cart'
#
# urlpatterns = [
#     path('cart/',views.cart , name='cart'),
#     path('add/' , views.add , name='add'),
#     path('edit/', views.edit , name='edit'),
#     path('delete', views.delete , name='delete'),
# ]

homepage/urls.py
from django.urls import path
from homepage import views
app_name = 'homepage'
urlpatterns = [
     path('home/',views.home , name = 'home'),
    path('message_board/' , views.message_board , name = 'message_board'),
    path('create/' ,views.create , name = 'create'),
    path('save/' , views.save , name = 'save'),
    path('search/', views.search ,name='search' ),
    path('showImg/',views.showImg , name = 'showImg'),
]

系统设计/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls' , namespace= 'login')),
    path('captcha/', include('captcha.urls')),
    path('homepage/',include('homepage.urls', namespace= 'homepage')),
    path('sale_good/',include('sale_good.urls' , namespace = 'sale_good')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
#encoding: utf-8
from django.db import models
#留言板模块
class Message(models.Model):
    username=models.CharField(max_length=256)
    title=models.CharField(max_length=512)
    content=models.TextField(max_length=256)
    publish=models.DateTimeField()

    class Meta:

        verbose_name = "留言板"
        verbose_name_plural = "留言板"

#为了显示
    def __str__(self):
        tpl = '用户:{username},    标题：{title},    内容：{content},    时间：{publish}'
        return tpl.format(username=self.username, title=self.title, content=self.content, publish=self.publish)

homepage/forms.py
from django import forms

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.conf import settings
from . import models
from . import forms
import datetime
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
#留言板功能
def message_board(request):
    messages = models.Message.objects.all()    #将数据库里的留言信息表示在留言板上
    return render(request, 'homepage/message_board.html', {'messages' : messages})
def create(request):
    return render(request, 'homepage/create.html')
def save(request):
    username = request.POST.get("username")
    title = request.POST.get("title")
    content = request.POST.get("content")
    publish = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    message = models.Message(title=title, content=content, username=username, publish=publish)
    message.save()
    return HttpResponseRedirect('/homepage/message_board/')

def home(request):
    return render(request,'homepage/home.html')

def search(request):
    #strip 去除空格等
    search_word = request.GET.get('wd','').strip()
    condition = None
    #分词：按空格  $(and) |(or) ~(not)
    for word in  search_word.split(' '):
        if condition is None:
            condition = Q(title_icontains=word)
        else:
            condition = condition | Q(title_icontains=word)
    search_message = []
    if condition is not None:
        # 筛选：搜索
        search_message = models.Message.objects.filter(title__icontains=search_word)
    #分页
    paginator = Paginator(search_message,20)
    page_num = request.GET.get('page',1)
    page_of_message = paginator.get_page(page_num)

    context = {}
    context['search_word'] = search_word
    context['search_message_count'] = search_message.count()
    context['page_of_message'] = page_of_message
    return render(request,'homepage/search.html',context)


def showImg(request):
    imgs =models.Photo.objects.all() # 从数据库中取出所有的图片路径
    context = {
        'imgs' : imgs
    }
    return render(request, 'homepage/home.html', locals())

templates/homepage/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言页面</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
<h3>留言板</h3> <!--h1-> h6-->
        <!--method: POST /GET -->
        <form action="/homepage/save/" method="POST" novalidate="novalidate">
	    {% csrf_token %}
            <table class="table table-striped table-bordered table-hover table-condensed">
				<label>用户名:</label> <input type="text" name="username" placeholder="用户名"  value="{{ request.session.user_name }}"/> <br /><br />
	            <label>标  题:</label> <input type="text" name="title" placeholder="标题" /><br /><br />
	            <label>内  容:</label> <textarea name="content" placeholder="内容"> </textarea><br /><br />
            </table>
            <input class="btn btn-success" type="submit" value="留言"/>
        </form>
{% endblock %}
</body>
</html>

templates/homepage/message_board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言板</title>
</head>
<body>

{% extends "base.html" %}
{% block content %}

    <table class="table table-striped table-bordered table-hover table-condensed">
            <thead>
                <tr class="danger">
                    <th>留言时间</th>
                    <th>留言者</th>
                    <th>标题</th>
                    <th>内容</th>
                </tr>
            </thead>
            <tbody>
                {% if messages %}
                    {% for message in messages %}
                        <tr class="{% cycle 'active' 'success' 'warning' 'info' %}">
                            <td>{{ message.publish|date:'Y-m-d H:i:s' }}</td>
                            <td>{{ message.username }}</td>
                            <td>{{ message.title }}</td>
                            <td>{{ message.content }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="4">无数据</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <a class="btn btn-xs btn-info" href="{% url 'homepage:create' %}">去留言</a>

{% endblock %}
</body>
</html>

templates/homepage/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索页面</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% if search_word == '' %}
                    <h1>您没有输入搜索内容</h1>
                    <p>你可以试着输入文字，如：书本</p>
                {% else %}
                    <h1>搜索“{{ search_word }}”,找到{{ search_message_count }}个结果</h1>
                    <hr>
                    {% for message in page_of_message %}
                        <a href="{% url 'homepage:message_board' %}"></a>
                        <p>{{ message.content | striptags }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    <div class="row" style="display: flex;justify-content: center;">
        {% if page_of_message.has_previous %}
            <a class="btn btn-default" href="{% url 'homepage:search' %}?wd={{ search_word }}&page={{ page_of_message.previous_page_number }}">
            上一页
            </a>
        {% endif %}
        {% if page_of_message.has_next %}
            <a class="btn btn-default" href="{% url 'homepage:search' %}?wd={{ search_word }}&page={{ page_of_message.next_page_number }}">
            下一页
            </a>
        {% endif %}
    </div>
    </div>
{% endblock %}
</body>
</html>