cart/urls.py
# from django.urls import path
# from cart import views
#
# app_name = 'cart'
#
# urlpatterns = [
#     path('cart/',views.cart , name='cart'),
#     path('add/' , views.add , name='add'),
#     path('edit/', views.edit , name='edit'),
#     path('delete', views.delete , name='delete'),
# ]

sale_good/urls.py
from django.urls import path
from sale_good import views

app_name = 'sale_good'
urlpatterns = [
    path('saleindex/', views.saleindex , name = 'saleindex'),
    path('salegood/',views.salegood, name = 'salegood'),
    path('showImg/' , views.showImg , name = 'showImg' ),
]

系统设计/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls' , namespace= 'login')),
    path('captcha/', include('captcha.urls')),
    path('homepage/',include('homepage.urls', namespace= 'homepage')),
    path('sale_good/',include('sale_good.urls' , namespace = 'sale_good')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sale_good/models.py
from django.db import models
from login.models import User
# Create your models here.
class salegood(models.Model):
    description = models.TextField(max_length=256)
    img_url = models.ImageField(upload_to='img') # upload_to指定图片上传的途径，如果不存在则自动创建
    name = models.CharField(max_length=200)
    item_type = (
        ('book', '书本类'),
        ('food','食品类'),
        ('res', '物品类'),
        ('necessary', '日用品类'),
        ('other', '其他'),
    )
    money = models.CharField(max_length=20)
    email = models.EmailField()
    sort = models.CharField(max_length=32,choices=item_type,default='书本类')

    class Meta:
        verbose_name = '出售货物信息'
        verbose_name_plural= '出售货物信息'

    def __str__(self):
        tpl = '物品类别：{sort},图片：{img_url},邮箱：{email},价格：{money}'
        return tpl.format(sort=self.sort,img_url=self.img_url,email=self.email,money=self.money)

sale_good/forms.py
from django import forms

# 表单类用以生成表单
class AddForm(forms.Form):
    # name = forms.CharField()
    headimg = forms.FileField()

class PriceForm(forms.Form):
    item_type = (
        ('book','书本类'),
        ('res','物品类'),
        ('necessary','日用品类'),
        ('other','其他'),
    )
    salemoney = forms.FloatField(label='金额',max_value=250 ,widget=forms.TextInput(attrs = {'class':'form-control'}))
    email = forms.EmailField(label="邮箱地址",max_length=250 , widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sort = forms.ChoiceField(label='物品种类',choices=item_type)

sale_good/views.py
from django.shortcuts import render, redirect
from . import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

def saleindex(request):
    return render(request,'sale_good/sale_good.html',locals())
def salegood(request):
    if request.method == 'POST':
    #描述的信息、图片
        content = request.POST.get('content')
        img = request.FILES.get('img')
        name = request.FILES.get('img').name
    #金额种类
        money = request.POST.get('money')
        email = request.POST.get('email')
        sort = request.POST.get('sort')
        sme = models.salegood( description=content, money = money , email = email, sort = sort ,img_url=img,name=name)
        sme.save()
    return render(request,'sale_good/sale_good.html',locals())
# 主页显示缩略图
def showImg(request):
    imgs =models.salegood.objects.all() # 从数据库中取出所有的图片路径
    sort = models.salegood.objects.all().values('sort')

    context = {
        'imgs' : imgs,
        'sort' : sort
    }
    return render(request, 'sale_good/showImg.html', locals())


# 分页
def listing(request):
    contact_list = models.salegood.objects.all()
    paginator = Paginator(contact_list, 3) # 每页显示25条

    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # 如果请求的页数不是整数，返回第一页。
        contacts = paginator.page(1)
    except EmptyPage:
        # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'sale_good/showImg.html', {'contacts': contacts})

templates/sale_good/details.html
{% extends 'base.html' %}
{% block title %}物品详细{% endblock %}

{% block content %}
{#    左侧图片#}
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
                <img alt="" src="{{ goods.img_url }}" class="img-polaroid"  style="width: 100px;height: 100px"/>
		</div>
	</div>
</div>
{#    右侧详细信息#}
    <div>

    </div>
{#    底部居中按钮#}
    <div>
    <button class="btn btn-primary" type="button">购买</button>
    </div>
{% endblock %}

templates/sale_good/indexpay.html
{% extends 'base.html' %}
{% block title %}支付页面{% endblock %}

{% block content %}
    <form action="/sale_good/pay/">
        <input type="text" name="money">
        <input type="submit" value="支付">
    </form>

{% endblock %}

templates/sale_good/sale_good.html
{% extends "base.html" %}
{% block title %}出售物品{% endblock %}
{% block content %}

    <div>
        <blockquote>
            <p>
				在这里你可以出售你想要出售的物品
            </p> <small>出售 <cite>物品</cite></small>
		</blockquote>
    </div>
<div>
       <form action="{% url 'sale_good:salegood'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
               {# 输入交易金额 #}
    <label >交易金额:</label><input type="text" name="money"><br /><br />
         {#     输入联系邮箱#}
    <label >联系邮箱:</label><input type="text" name="email"><br /><br />
        {#     选择种类#}
    <select name="sort">
          <option value="none" selected disabled hidden>种类选择</option>
          <option value="book">书本类</option>
          <option value="food">食品类</option>
          <option value="res">物品类</option>
          <option value="necessary">日用品类</option>
          <option value="other">其他类</option>
    </select>
         <br /><br />
    <input type="file" name="img" >
    <div class="form-group" >
		<label for="name">这里输入物品的详细描述</label>
        <br>
		 <textarea  name="content" placeholder="详细描述" style="width: 529px;height: 104px"></textarea>
	</div>
    <button type="submit" class="btn btn-info" onclick="mesbox()">确定</button>
        </table>
     </form>
    <script language="JavaScript">
    function mesbox() {
        alert("提交成功");
    }
    </script>
</div>
{% load static %}
    <div class="photo"><img src="{% static 'sale_good/image/saleright.jpg' %}" alt="通用占位符" style="float: right;width: 650px;height: 430px;margin: -440px 20px 40px 30px"></div>
{% endblock %}

templates/sale_good/showImg.html
{% extends "base.html" %}
{% block title %}闲置二手物品销售平台{% endblock %}
{% block content %}

<div class="tabbable tabs-below" id="tabs-972946"> <!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#panel-125424" data-toggle="tab">书本类</a>
        </li>
        <li class="">
            <a href="#panel-947621" data-toggle="tab">食品类</a>
        </li>
        <li class="">
            <a href="#panel-947622" data-toggle="tab">物品类</a>
        </li>
        <li class="">
            <a href="#panel-947623" data-toggle="tab">日用品类</a>
        </li>
        <li class="">
            <a href="#panel-947624" data-toggle="tab">其他</a>
        </li>
    </ul>
{#书本类内容#}
    <div class="tab-content">
        <div class="tab-pane active" id="panel-125424"  >
            <div class="row" id="panel-125424" >
                {% for item in imgs %}
                    {% if item.sort == 'book' %}
                        <div class="col-sm-4 col-md-4" >    {# 写在这里面就是每个都换行了 #}
                            <div class="thumbnail" >
                                <img src="{{ item.img_url.url }}" alt="#" style="height: 300px;width: 350px" >
                                    <div class="caption">
                                        <h3 style="font-size: 20px">联系邮箱：<span>{{ item.email }}</span></h3>
                                        <p style="font-size: 20px">出售价格：<span style="color: #ac2925;font-size: 25px">{{ item.money }}</span> 元</p>
                                        <p><span>物品概述：</span>{{ item.description }}</p>
                                        <p>
                                            <a class="btn btn-primary" href="#"  type="button" >
                                                购买
                                            </a>
                                        </p>
                                    </div>
                            </div>
                         </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

{#   食品类内容#}
    <div class="tab-pane" id="panel-947621" >
        <div class="row" id="panel-947621" >
                {% for item in imgs %}
                    {% if item.sort == 'food' %}
                        <div class="col-sm-4 col-md-4" >    {# 写在这里面就是每个都换行了 #}
                            <div class="thumbnail" >
                                <img src="{{ item.img_url.url }}" alt="#" style="height: 300px;width: 350px" >
                                    <div class="caption">
                                        <h3 style="font-size: 20px">联系邮箱：<span>{{ item.email }}</span></h3>
                                        <p style="font-size: 20px">出售价格：<span style="color: #ac2925;font-size: 25px">{{ item.money }}</span> 元</p>
                                        <p><span>物品概述：</span>{{ item.description }}</p>
                                        <p>
                                            <a class="btn btn-primary" href="#"  type="button" >
                                                购买
                                            </a>
                                        </p>
                                    </div>
                            </div>
                         </div>
                    {% endif %}
                {% endfor %}
            </div>
    </div>

{#  物品类内容 #}
    <div class="tab-pane" id="panel-947622" >
      <div class="row" id="panel-947622" >
                {% for item in imgs %}
                    {% if item.sort == 'res' %}
                        <div class="col-sm-4 col-md-4" >    {# 写在这里面就是每个都换行了 #}
                            <div class="thumbnail" >
                                <img src="{{ item.img_url.url }}" alt="#" style="height: 300px;width: 350px" >
                                    <div class="caption">
                                        <h3 style="font-size: 20px">联系邮箱：<span>{{ item.email }}</span></h3>
                                        <p style="font-size: 20px">出售价格：<span style="color: #ac2925;font-size: 25px">{{ item.money }}</span> 元</p>
                                        <p><span>物品概述：</span>{{ item.description }}</p>
                                        <p>
                                            <a class="btn btn-primary" href="#"  type="button" >
                                                购买
                                            </a>
                                        </p>
                                    </div>
                            </div>
                         </div>
                    {% endif %}
                {% endfor %}
            </div>
    </div>
{#  日用品类内容#}
    <div class="tab-pane" id="panel-947623" >
      <div class="row" id="panel-947623" >
                {% for item in imgs %}
                    {% if item.sort == 'necessary' %}
                        <div class="col-sm-4 col-md-4" >    {# 写在这里面就是每个都换行了 #}
                            <div class="thumbnail" >
                                <img src="{{ item.img_url.url }}" alt="#" style="height: 300px;width: 350px" >
                                    <div class="caption">
                                        <h3 style="font-size: 20px">联系邮箱：<span>{{ item.email }}</span></h3>
                                        <p style="font-size: 20px">出售价格：<span style="color: #ac2925;font-size: 25px">{{ item.money }}</span> 元</p>
                                        <p><span>物品概述：</span>{{ item.description }}</p>
                                        <p>
                                            <a class="btn btn-primary" href="#"  type="button" >
                                                购买
                                            </a>
                                        </p>
                                    </div>
                            </div>
                         </div>
                    {% endif %}
                {% endfor %}
            </div>
    </div>
{#   其他类#}
    <div class="tab-pane" id="panel-947624" >
      <div class="row" id="panel-947624" >
                {% for item in imgs %}
                    {% if item.sort == 'other' %}
                        <div class="col-sm-4 col-md-4" >    {# 写在这里面就是每个都换行了 #}
                            <div class="thumbnail" >
                                <img src="{{ item.img_url.url }}" alt="#" style="height: 300px;width: 350px" >
                                    <div class="caption">
                                        <h3 style="font-size: 20px">联系邮箱：<span>{{ item.email }}</span></h3>
                                        <p style="font-size: 20px">出售价格：<span style="color: #ac2925;font-size: 25px">{{ item.money }}</span> 元</p>
                                        <p><span>物品概述：</span>{{ item.description }}</p>
                                        <p>
                                            <a class="btn btn-primary" href="#"  type="button" >
                                                购买
                                            </a>
                                        </p>
                                    </div>
                            </div>
                         </div>
                    {% endif %}
                {% endfor %}
            </div>
    </div>
{# 5结束#}

{#分页#}
{% for contact in contacts %}
    {# 每个"contact"都是一个Contact模型对象. #}
    {{ contact.full_name|upper }}<br />
    <div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endfor %}



{#    切换卡结束#}
    </div>
</div>


{% endblock %}